---
- hosts: localhost
  gather_facts: no
  #remote_user: root
  #remote_user: root
  #become: yes
  #become_method: sudo

  tasks:
  - name: mount nfs datastore iso
    vmware_host_datastore:
      hostname: "{{ esxi_hostname }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      #hosts: "{{ esxi }}"
      esxi_hostname: "{{ esxi }}"
      hosts: "{{ esxi }}"
      validate_certs: no
      datastore_name: "{{ name }}"
      datastore_type: "{{ nfs_type }}"
      nfs_server: "{{ nfs_server }}"
      nfs_path: "{{ nfs_path }}"
      nfs_ro: no
      state: present
    delegate_to: localhost

